### PR TITLE
Recursively parse folder

### PR DESCRIPTION
**Pull request by tzi**
Hi!

I made a little improvement to parse folders recursively.

According to the comments in #41, it could not be the purpose of this tool.
But I think it could be great for parker:
- It behaves more naturally when we start using it
- Usage it simple: `parker <path/to/the/root/folder/of/your/project>`
- It adds a feature and there is no compatibility break

Cheers,
Thomas.

### CODE REVIEW

**Comment by tzi** [comment]
Hi!

If you have some time available, I liked to have feedback on this PR ;)

Have a nice day!
Thomas.

**Comment by seangates** [comment]
👍  for this, as we have page-specific compiled CSS files which we would like to test all at once.

**Comment by katiefenn** [comment]
Hi there @tzi, thank you for your PR. I'm working on Parker and hope to have a new version available soon. I'm sorry it has taken so long!

This looks like a straightforward change to introduce a useful feature, I am happy to merge it.

**Comment by tzi** [comment]
Nice!
Thanks you for merging it :fireworks: 

Cheers,
Thomas.

**Pull request merged**
